# Generated by Django 3.1.5 on 2021-02-08 23:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import forums.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=150)),
                ('ordering', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('threads', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
                ('ordering', models.IntegerField(blank=True, null=True)),
                ('latest_thread_time', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=forums.models.Category, to='forums.category')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('viewed', models.CharField(max_length=500)),
                ('author', models.OneToOneField(on_delete=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('threads', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
                ('ordering', models.IntegerField(blank=True, null=True)),
                ('latest_thread_time', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=forums.models.Forum, to='forums.forum')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=1000)),
                ('labels', models.CharField(max_length=500)),
                ('viewed', models.CharField(max_length=500)),
                ('closed', models.BooleanField(blank=True, default=False)),
                ('latest_post_time', models.DateTimeField(blank=True, null=True)),
                ('author', models.OneToOneField(on_delete=django.contrib.auth.models.User, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=forums.models.Forum, to='forums.forum')),
                ('subforum', models.ForeignKey(blank=True, null=True, on_delete=forums.models.SubForum, to='forums.subforum')),
            ],
        ),
        migrations.DeleteModel(
            name='ForumPermission',
        ),
        migrations.AddField(
            model_name='reply',
            name='thread',
            field=models.ForeignKey(on_delete=forums.models.Thread, to='forums.thread'),
        ),
    ]
